name = "risenext"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"


# D1 Database configuration
[[ d1_databases ]]
binding = "DB"
database_name = "risenext-db"
database_id = "95c56d57-4f6b-4280-a3b8-0d52a0c178ad"
migrations_dir = "drizzle"

# R2 Storage configuration
[[r2_buckets]]
binding = 'R2_BUCKET'
bucket_name = 'rise-next'
preview_bucket_name = 'rise-next'

# KV configuration
[[kv_namespaces]]
binding = "KV"
id = "173e401e75ca4ebf8ba12d1b6e1f758c"
preview_id = "173e401e75ca4ebf8ba12d1b6e1f758c"